# Generated by Django 5.2.16 on 2026-07-09 07:16

# Django
from django.db import migrations, models

# AA Bulletin Board
import aa_bulletin_board.models


class Migration(migrations.Migration):

    dependencies = [
        ("aa_bulletin_board", "0006_switch_to_ckeditor_5"),
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("groupmanagement", "0021_alter_authgroup_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.SET(aa_bulletin_board.models.get_sentinel_user),
                related_name="+",
                to="authentication.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="bulletin",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="aa_bulletin_board_group_restriction",
                to="groupmanagement.group",
                verbose_name="Group restrictions",
            ),
        ),
    ]
